<?php

namespace Asaas\Resources\Webhook\Enum;

enum WebhookEventsEnum: string
{
    case PAYMENT_CREATED = 'PAYMENT_CREATED';
    case PAYMENT_UPDATED = 'PAYMENT_UPDATED';
    case PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED';
    case PAYMENT_RECEIVED = 'PAYMENT_RECEIVED';
    case PAYMENT_OVERDUE = 'PAYMENT_OVERDUE';
    case PAYMENT_DELETED = 'PAYMENT_DELETED';
    case PAYMENT_AWAITING_RISK_ANALYSIS = 'PAYMENT_AWAITING_RISK_ANALYSIS';
    case PAYMENT_APPROVED_BY_RISK_ANALYSIS = 'PAYMENT_APPROVED_BY_RISK_ANALYSIS';
    case PAYMENT_REPROVED_BY_RISK_ANALYSIS = 'PAYMENT_REPROVED_BY_RISK_ANALYSIS';
    case PAYMENT_AUTHORIZED = 'PAYMENT_AUTHORIZED';
    case PAYMENT_CREDIT_CARD_CAPTURE_REFUSED = 'PAYMENT_CREDIT_CARD_CAPTURE_REFUSED';
    case PAYMENT_ANTICIPATED = 'PAYMENT_ANTICIPATED';
    case PAYMENT_RESTORED = 'PAYMENT_RESTORED';
    case PAYMENT_REFUNDED = 'PAYMENT_REFUNDED';
    case PAYMENT_PARTIALLY_REFUNDED = 'PAYMENT_PARTIALLY_REFUNDED';
    case PAYMENT_REFUND_IN_PROGRESS = 'PAYMENT_REFUND_IN_PROGRESS';
    case PAYMENT_RECEIVED_IN_CASH_UNDONE = 'PAYMENT_RECEIVED_IN_CASH_UNDONE';
    case PAYMENT_CHARGEBACK_REQUESTED = 'PAYMENT_CHARGEBACK_REQUESTED';
    case PAYMENT_CHARGEBACK_DISPUTE = 'PAYMENT_CHARGEBACK_DISPUTE';
    case PAYMENT_AWAITING_CHARGEBACK_REVERSAL = 'PAYMENT_AWAITING_CHARGEBACK_REVERSAL';
    case PAYMENT_DUNNING_RECEIVED = 'PAYMENT_DUNNING_RECEIVED';
    case PAYMENT_DUNNING_REQUESTED = 'PAYMENT_DUNNING_REQUESTED';
    case PAYMENT_BANK_SLIP_VIEWED = 'PAYMENT_BANK_SLIP_VIEWED';
    case PAYMENT_CHECKOUT_VIEWED = 'PAYMENT_CHECKOUT_VIEWED';
    case PAYMENT_SPLIT_CANCELLED = 'PAYMENT_SPLIT_CANCELLED';
    case PAYMENT_SPLIT_DIVERGENCE_BLOCK = 'PAYMENT_SPLIT_DIVERGENCE_BLOCK';
    case PAYMENT_SPLIT_DIVERGENCE_BLOCK_FINISHED = 'PAYMENT_SPLIT_DIVERGENCE_BLOCK_FINISHED';
}
