#!/usr/bin/env sh

KN='\033[0m'
BBlue='\033[1;34m'
BRed='\033[1;31m'

REGEX_ISSUE_ID="[a-zA-Z0-9,._-]+-[0-9]+"

BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")
COMMIT_MESSAGE=$(cat "$1")

if [ -z "$ISSUE_ID" ]; then
    echo "🛑 ${BRed} Branch name does not follow the expected pattern...${KN}"
    exit 1
fi

case "$COMMIT_MESSAGE" in
    "$ISSUE_ID"*)
        exit 0
        ;;
esac

echo "$ISSUE_ID: $COMMIT_MESSAGE" > "$1"
